# Generated by Django 5.1.1 on 2024-10-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
